Repository BRAVO68WEB/url-minify, pull requests merged in 2022-03, with the labels that each got.

#80 fix(#76): remove direct use of req.body.
  backend/controllers/minify.js
Labels: easy, good first issue, GSSOC 22

#92 Add Page Loader fixes #92
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_app.js
  frontend/styles/globals.css
  frontend/yarn.lock
Labels: enhancement, easy, good first issue, GSSOC22, Level1

#90 Added Functionality to View All Links created by a User [Frontend]
  frontend/components/Dashboard/Dashboard.jsx
  frontend/components/Dashboard/Dashboard.style.js
  frontend/components/Dashboard/myLink.jsx
  frontend/components/Dashboard/myLink.style.js
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/myLinks/index.js
  frontend/yarn.lock
  package-lock.json
Labels: medium, GSSOC22, Level2

#99 User registration
  backend/index.js
  frontend/components/Reg/Reg.jsx
  frontend/helpers/user/userState.js
  frontend/helpers/user/usercontext.js
  frontend/package.json
  frontend/pages/_app.js
  package-lock.json
Labels: medium, GSSOC22, Level2

#102 Enhanced Documentation
  README.md
Labels: easy, GSSOC22, Level1

#104 Update HOW_TO_CONTRIBUTE.md
  HOW_TO_CONTRIBUTE.md
Labels: spam

#110 Modified the 404 page(#103)
  frontend/components/HomeSection/HomeSection.style.js
  frontend/pages/404.js
  frontend/pages/index.js
  frontend/styles/404.css
Labels: good first issue, GSSOC22, Level2

#114 Updated Feature Section(#111)
  frontend/components/Features/index.js
  frontend/pages/index.js
  frontend/styles/Features.module.css
  frontend/styles/HomeSection.module.css
Labels: enhancement, easy, GSSOC22

#113 Sidebar visibility.
  frontend/components/Dashboard/Dashboard.style.js
Labels: bug, enhancement, GSSOC22

#120 Added Start Again Button(#118)
  frontend/components/HomeSection/HomeSection.jsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/index.js
  frontend/yarn.lock
Labels: enhancement, easy, good first issue, Level1

#126 fix(#84) Prevent Duplication of Alias
  backend/controllers/minify.js
  backend/routers/minify.js
Labels: enhancement, GSSOC22, Level2

#87 fix(#83): add method to verify if alias being use is blacklisted or not.
  backend/controllers/minify.js
Labels: enhancement, medium, GSSOC22, Level2
