Repository BRAVO68WEB/url-minify, pull requests merged in 2022-02, with the labels that each got.

#20 Delete a particular record by Id
  backend/controllers/minify.js
  backend/routers/minify.js
  backend/yarn.lock
Labels: medium, JWOC

#27 Added logo and favicon
  frontend/components/NavBar/Logo.js
  frontend/components/NavBar/index.js
  frontend/pages/_app.js
  frontend/public/favicon.ico
  frontend/styles/globals.css
  frontend/styles/logostyles.css
  frontend/yarn.lock
Labels: medium, JWOC

#32 Feature/auth backend
  backend/.env.example
  backend/controllers/user.js
  backend/middlewares/auth.js
  backend/models/user.js
  backend/package.json
  backend/routers/index.js
  backend/routers/user.js
  backend/yarn.lock
Labels: JWOC, hard

#35 Added a Text box and a submit button
  frontend/components/HomeSection/HomeSection.style.js
  frontend/components/HomeSection/homeSection.jsx
  frontend/pages/index.js
Labels: medium, JWOC

#42 Sign Up created
  frontend/assets/bg/main-bg.png
  frontend/assets/icons/email-line.svg
  frontend/assets/icons/lock-line.svg
  frontend/assets/icons/user-line.svg
  frontend/components/HomeSection/homeSection.jsx
  frontend/components/NavBar/index.js
  frontend/components/Reg/Reg.jsx
  frontend/components/Reg/Reg.style.js
  frontend/components/Reg/styles.css
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_app.js
  frontend/pages/index.js
  frontend/pages/signup.js
  frontend/styles/globals.css
  frontend/yarn.lock
Labels: bug, JWOC, hard

#46 Post request to add minified alias
  backend/index.js
  frontend/components/HomeSection/homeSection.jsx
  frontend/package.json
  frontend/pages/index.js
Labels: medium, JWOC

#49 Feature/axios handler
  backend/pnpm-lock.yaml
  frontend/.env
  frontend/components/HomeSection/homeSection.jsx
  frontend/helpers/Axios.js
  frontend/package.json
  frontend/pnpm-lock.yaml
Labels: medium, JWOC

#69 404 Page Made
  frontend/components/Features/index.js
  frontend/components/HomeSection/homeSection.jsx
  frontend/components/NavBar/index.js
  frontend/package-lock.json
  frontend/pages/404.js
  frontend/pages/_app.js
  frontend/styles/404.css
  frontend/styles/index.css
  frontend/yarn.lock
Labels: medium, JWOC

#70 created sidebar for dashboard
  frontend/components/Dashboard/Dashboard.jsx
  frontend/components/Dashboard/Dashboard.style.js
  frontend/pnpm-lock.yaml
Labels: medium, JWOC
